site_name: Dropt

pages:
- Introduction: index.md
- ChangeLog: changelog.md
- Configuration Files: configuration.md
- Commands: commands.md
- Under the Hood: howitworks.md
- Debugging: debugging.md
- Examples:
  - Simple Replacement: examples/simple_replacement.md
- ZenScript:
  - Dropt: zs/dropt.md
  - RuleList: zs/rulelist.md
  - Rule: zs/rule.md
  - Harvester: zs/harvester.md
  - Drop: zs/drop.md
  - Examples: zs/example.md
- JSON:
  - Syntax: json/syntax.md
  - Examples: json/examples.md
- API:
  - Reference: api/reference.md
- Development:
  - Contributor's License Agreement: cla.md

theme: readthedocs

markdown_extensions:
- admonition
- attr_list

extra_css: [custom.css]